// ==== Action constants ====
export const ADD_FIRST_AND_SECOND_NAMES = 'ADD_FIRST_AND_SECOND_NAMES';
export const ADD_USER_DATE = 'ADD_USER_DATE';
export const ADD_USER_STATUS = 'ADD_USER_STATUS';
export const ADD_LOADED = 'ADD_LOADED';
export const ADD_USER_ID = 'ADD_USER_ID';
export const ADD_USER_PHOTO = 'ADD_USER_PHOTO';

export const ADD_USERS_FIRST_AND_SECOND_NAMES =
  'ADD_USERS_FIRST_AND_SECOND_NAMES';
export const ADD_USERS_DATE = 'ADD_USERS_DATE';
export const ADD_USERS_STATUS = 'ADD_USERS_STATUS';
export const ADD_USERS_LOADED = 'ADD_USERS_LOADED';
export const ADD_USERS_PHOTO = 'ADD_USERS_PHOTO';
export const ADD_USERS_FOLLOWING_COUNT = 'ADD_USERS_FOLLOWING_COUNT';
export const ADD_USERS_FOLLOWERS_COUNT = 'ADD_USERS_FOLLOWERS_COUNT';
export const ADD_USERS_IS_FRIEND = 'ADD_USERS_IS_FRIEND';

export const ADD_USER_IN_SEARCH = 'ADD_USER_IN_SEARCH';
export const ADD_USER_SEARCH_LOADED = 'ADD_USER_SEARCH_LOADED';

export const ADD_USERS_CHATS = 'ADD_USERS_CHATS';
export const CLEAR_CHAT_STATE = 'CLEAR_CHAT_STATE';

export const GET_POST = 'GET_POST';
export const GET_USERS_POST = 'GET_USERS_POST';
export const CLEAN_POSTS = 'CLEAN_POSTS';
export const CLEAN_USERS_POSTS = 'CLEAN_USERS_POSTS';
